export const ESP32_COMMON_PINS = [
  { value: "2", label: "GPIO 2 (چراغ ال‌دی توکار برد)" },
  { value: "4", label: "GPIO 4 (پایه عمومی دیجیتال)" },
  { value: "5", label: "GPIO 5 (رله یا خروجی جریان بالا)" },
  { value: "12", label: "GPIO 12 (پایه دیجیتال عمومی)" },
  { value: "13", label: "GPIO 13 (پایه دیجیتال عمومی)" },
  { value: "14", label: "GPIO 14 (پایه شیفت ریجستر/خط ترانزیستور)" },
  { value: "15", label: "GPIO 15 (کنترل بوق هشداری)" },
  { value: "16", label: "GPIO 16 (پایه فرستنده/گیرنده سریال ۲)" },
  { value: "17", label: "GPIO 17 (پایه فرستنده/گیرنده سریال ۲)" },
  { value: "18", label: "GPIO 18 (پروتکل ارتباطی SPI SCK)" },
  { value: "19", label: "GPIO 19 (پروتکل ارتباطی SPI MISO)" },
  { value: "21", label: "GPIO 21 (پروتکل ارتباطی I2C SDA)" },
  { value: "22", label: "GPIO 22 (پروتکل ارتباطی I2C SCL)" },
  { value: "23", label: "GPIO 23 (پروتکل ارتباطی SPI MOSI)" },
  { value: "25", label: "GPIO 25 (مبدل صوتی یا خروجی آنالوگ DAC1)" },
  { value: "26", label: "GPIO 26 (مبدل صوتی یا خروجی آنالوگ DAC2)" },
  { value: "27", label: "GPIO 27 (پایه دیجیتال عمومی)" },
  { value: "32", label: "GPIO 32 (پایه دیجیتال عمومی)" },
  { value: "33", label: "GPIO 33 (پایه دیجیتال عمومی)" },
];
